---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role vhost
# 
# Overview:
#
# This task is to contain tasks that should be run in vhost
# vitualation environments like AWS and Vagrant, but not in
# containers.  You typically would not run this role
# independently
#
# Dependencies:
# - common
# 

- name: Copy the templates to their respestive destination
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: root 
    group: root 
    mode: "{{ item.mode | default(644) }}"
  register: config_templates
  with_items:
    - { src: 'etc/{{ COMMON_MOTD_TEMPLATE }}', dest: '/etc/motd.tail', mode: '755' }
    - { src: 'etc/ssh/sshd_config.j2', dest: '/etc/ssh/sshd_config' }
    
- name: restart ssh
  service: name=ssh state=restarted
  sudo: True
  when: config_templates.changed

- name: Add script for syncing logs on exit
  template:
    src: sync-logs-on-exit.j2
    dest: "{{ COMMON_OBJECT_STORE_LOG_SYNC_ON_EXIT }}"
    owner: root
    group: root
    mode: 0744
  when: COMMON_OBJECT_STORE_LOG_SYNC

# With systemd, log rotation should be run with an `ExecStop` directive
# of `syslog.service` to ensure that rsyslogd will not be killed before attempt
# of syncing logs.
- name: Force logrotate on syslog stop
  lineinfile:
    path: /etc/systemd/system/syslog.service
    line: "ExecStop={{ COMMON_OBJECT_STORE_LOG_SYNC_ON_EXIT }}"
    insertafter: "^ExecStart=.*$"
  when: COMMON_OBJECT_STORE_LOG_SYNC
        and ansible_distribution_release != 'precise'
        and ansible_distribution_release != 'trusty'